name: fazmatricula
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.2
  http: ^0.12.0+4
  permission: ^0.1.7


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:


  uses-material-design: true



  assets:
    - assets/logo.png
    - assets/logo2.png
    - assets/messi.jpg
    - assets/messi2.png
    - assets/iconApp.png
